config/routes.rb
NewsReader3::Application.routes.draw do
  
  resources :keywords

  resources :categories

  resources :genres

  resources :articles

  root :to => "articles#index"

  

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :category
  has_many :keywords
  
end#class Genre < ActiveRecord::Base

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  
  layout 'admin'
  
  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all

    target = "doc/mylog/log.log"
    # target = "log.log"
    
    # @content = "111111111"
    @content = ""
    
    if File.exists?(target)
      
      # File.open(target, "r") do |f|
#         
        # @contentArray = f.each_line {|line|}
        # # @content = f.read()
        # # f.write(content)
        # # f.write("\n")
      # end

      # => http://www.ruby-forum.com/topic/66733
      @contentArray = File.readlines(target)

    else
      
      @content = "abcdefg"
      
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genres }
    end
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
    @genre = Genre.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/new
  # GET /genres/new.json
  def new
    @genre = Genre.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genre }
    end
  end

  # GET /genres/1/edit
  def edit
    @genre = Genre.find(params[:id])
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(params[:genre])

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render json: @genre, status: :created, location: @genre }
      else
        format.html { render action: "new" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /genres/1
  # PUT /genres/1.json
  def update
    @genre = Genre.find(params[:id])

    respond_to do |format|
      if @genre.update_attributes(params[:genre])
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/_index_log.html.erb
<input type="button" value="Show log"   id="show_button" /> |
<!--
	REF disabled http://html.eweb-design.com/0903_btn.html
-->
<input type="button" value="Hide log"   class="hide_button" disabled/>

<div id="logs" style="display: none;">
	<a href="#bottom">To bottom</a>
	<br />

	<% if @contentArray != nil %>
		<% for i in 0..@contentArray.length - 1 %>
		
			<%= @contentArray[i] %><br />
		
		<% end %>

	<% else %>
		
		<%= @content %>
	
	<% end %>		
	
	<input type="button" value="Hide log"   class="hide_button" disabled/>
	
</div>

app/views/genres/_index_table.html.erb
<table>
  <tr>
  	<th>Id</th>
    <th>Name</th>
    <th>Code</th>
  </tr>

<% @genres.each do |genre| %>
  <tr>
  	<td><%= genre.id %></td>
    <td><%= link_to genre.name, genre %></td>
    <td><%= genre.code %></td>
  </tr>
<% end %>
</table>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Genres</h1>

	<%= render :partial => "index_table" %>
	
<br />

<%= link_to 'New Genre', new_genre_path %>

<hr />

<dl class="accordion">
	<dt>
		<span style="color: green">Admin data</span>
	</dt>
	
	<dd>
		session[:doc_num] => <%= session[:doc_num] %>
	</dd>
</dl>

<hr />

	<%= render :partial => "index_log" %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @genre.id %>
</p>

<p>
  <b>Name:</b>
  <%= @genre.name %>
</p>

<p>
  <b>Code:</b>
  <%= @genre.code %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>&nbsp;&nbsp;|&nbsp;
<%= link_to 'Destroy', @genre, confirm: 'Are you sure?', method: :delete , :style => "color: red;" %>