config/routes.rb
NewsReader3::Application.routes.draw do
  
  resources :keywords

  resources :categories

  resources :genres

  resources :articles

  root :to => "articles#index"

  

end

app/models/article.rb
class Article < ActiveRecord::Base
  
end

app/controllers/articles_controller.rb
#coding:utf-8

require 'nokogiri'
require 'open-uri'

require 'basics'
include BASICS

require 'utils'
# load 'utils'

class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
      #------------------------------
      # 1. Get number of docs
      # 2. Set genre
      # 3. Get objects
      # 3-2. Set "@genres"
      
      # 4. Set session objects
      #------------------------------
      #------------------------------
      # 1. Get number of docs
      #------------------------------
      number = get_num_of_docs()
      
      #----------------------
      # 2. Set genre
      #----------------------
      @genre = get_genre()

      #debug
      write_log(
                "genre=" + @genre,  
                # __FILE__,
                __FILE__.split("/")[-1],
                __LINE__.to_s)


      
      #----------------------
      # 3. Get objects
      #----------------------
      #//----------- try_3 -----------------
      @current_num = number
      
      @params = params

      # #debug
      # params_content = ""
#       
      # params.each_pair {|k, v|
#         
        # params_content += "(" + k + "=>" + v + ")"
#         
      # }
#       
      # write_log(
                # "params_content=" + params_content,  
                # # __FILE__,
                # __FILE__.split("/")[-1],
                # __LINE__.to_s)      
# 


      @kw = []
      
      if @genre == "int"
          
          @category_names = _get_category_names_int()

          write_log(
                "@category_names.size=" + @category_names.size.to_s,  
                # __FILE__,
                __FILE__.split("/")[-1],
                __LINE__.to_s)      

          @kw = set_category_names_and_keywords_int()
          
          # #debug
          # msg = ""
          # @kw[0].each {|k|
              # msg += k + "/"
          # }
#           
#           
          # write_log(
                # msg,  
                # # __FILE__,
                # __FILE__.split("/")[-1],
                # __LINE__.to_s)
#                               => 米国/米/アメリカ/ 
                      
      elsif @genre == "bus_all"
        
        set_category_names_and_keywords_bus()
        

      elsif @genre == "soci"
        
        set_category_names_and_keywords_soci()
        

        
      else 
        @category_names = ["All"]
      end
#       

      @objects = try_3(number, @genre)
      
      genres_src = Genre.all
      
      @genres = {}
      genres_src.each do |item|
        @genres[item.name] = item.code
      end
      

      #----------------------
      # 4. Set session objects
      #----------------------
      # REF => 黒田・佐藤：322
      session[:doc_num] = @current_num
      
      session[:genre] = @genre

  end#def index

  def _get_category_names_int()
    
      genre = Genre.find_by_code("int")
        
      write_log(
              "genre.name =>" + genre.name, 
              # __FILE__,
              __FILE__.split("/")[-1],
              __LINE__.to_s)
      
      if genre != nil
        
        categories = Category.find_all_by_genre_id(genre.id)
        
        write_log(
              "genre != nil => #{genre.name}", 
              # __FILE__,
              __FILE__.split("/")[-1],
              __LINE__.to_s)
        
        #debug
        if categories != nil
          
            write_log(
              "categories.size=" + categories.size.to_s, 
              # __FILE__,
              __FILE__.split("/")[-1],
              __LINE__.to_s)

              
        else
          
            write_log(
                "categories => nil", 
                # __FILE__,
                __FILE__.split("/")[-1],
                __LINE__.to_s)
          
        end
        
        
      else
        
        write_log(
              "genre == nil", 
              # __FILE__,
              __FILE__.split("/")[-1],
              __LINE__.to_s)


        
        # render :text "Genre wasn't found by the code 'int'"
        
      end
      
      # categories = Category.find_all_by_genre_id(3)
      
      category_names = []
      
      categories.each do |cat|
        
          category_names.append(cat.name)
        
      end
      
      category_names.append("Others")
      
      #debug
      write_log(
                "category_names.size=" + category_names.size.to_s, 
                # __FILE__,
                __FILE__.split("/")[-1],
                __LINE__.to_s)
        
      
      return category_names
      
  end#def _get_category_names_int()

  def set_category_names_and_keywords_soci
    
        @category_names = [
                              #"原発", "事件", "政治"
                              "Nuclear plants", "Incidents", "Political issues",
                              "韓国", "中国", "医療/介護", "災害", "Others"
                              ]
        
        # @kw[0] = ["原発", "福島", "", "東電", "東京電力", "原子力"]
        @kw[0] = ["原発", "福島", "東電", "東京電力", "原子力"] 
        
        # Incidents
        @kw[1] = ["殺人", "傷害", "盗撮", "事件", "逮捕", "いじめ", "女性"]
        
        @kw[2] = ["首相", "市長", "選挙"]
        
        @kw[3] = ["韓国", "竹島"]
        
        # 中国
        @kw[4] = ["中国", "尖閣", "日中"]
        
        # 医療/介護
        @kw[5] = ["介護", "がん", "感染", "食中毒", "けが", "出生", "風邪", "妊娠"]
        
        # 災害
        @kw[6] = ["防災", "高温", "津波"]    
    
  end#def set_category_names_and_keywords_soci

  def set_category_names_and_keywords_bus
        @category_names = [
                          "US", "China", "Europe", 
                          "Korea", "Middle east",
                          "Japan: Automobile",
                          "Japan: Electronics", 
                          "Energy",
                          "Securities, foreign exchanges",
                          "Others"]
        
        @kw[0] = ["米国", "米", "アメリカ"]
      
        @kw[1] = ["中国", "中"]
        
        @kw[2] = [
                        "ヨーロッパ", "欧州", "欧", "EURIBOR", "EURO", "ユーロ", 
                        "ロシア", "東欧", "ポーランド", 
                        "イギリス", "フランス", "ドイツ", 
                        "スペイン", "イタリア", "伊", "ポルトガル", 
                        ]
        
        @kw[3] = [
                        "韓国", "韓", "朝鮮",
                        "サムスン", "現代"
                        ]
        
        @kw[4] = ["イラン", "シリア", "イラク"]
        
        @kw[5] = [
                        "自動車", "乗用車",
                        "日産", "日野", "三菱自", "トヨタ", "ダイハツ", "ホンダ", "マツダ",
                        "ＢＭＷ", "BMW", "ベンツ"
                        ]
        
        @kw[6] = [
                          "ソニー", "パナソニック", "松下", "シャープ", "東芝", "三菱電",
                          "セイコー"
                          
                          ]
        
        @kw[7] = ["ガソリン", "ソーラー", "原油", "原発", "石油", "エネルギー", "発電", "火力"]
        
        @kw[8] = ["証券", "相場", "円", "日経平均", "ＥＵＲＩＢＯＲ"]
        
  end#def set_category_names_and_keywords_bus
  
  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  
  private #==========================================
    # ============ try_1 => From: try_nokogiri_17 ========================
  def get_atags(docs)
  #    # Get doc
  #    docs = get_docs(5)
  #    
  #    #meta_tags
  #    meta_tags = nil
  #    
  #    # New docs
  #    docs_new = []
  
      # href a tags
      a_tags_href = []
      
      vendor_list = []
      
      # #debug
      # get_next_sibling = true
      
      # Modify
      docs.each do |doc|
        #--------------------
        # Modify 'a' tags
        #--------------------
        
        # Get 'a' tags
        a_tags = doc.css("div ul li a")
        
        # href value
        a_tags.each do |a_tag|
          if a_tag['href'].start_with?("/hl?")
            # Modify url
            a_tag['href'] = "http://headlines.yahoo.co.jp" + a_tag['href']
            

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line %><br />
    <%= f.text_area :line %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :src %><br />
    <%= f.text_field :src %>
  </div>
  <div class="field">
    <%= f.label :news_time %><br />
    <%= f.text_field :news_time %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :cat %><br />
    <%= f.text_field :cat %>
  </div>
  <div class="field">
    <%= f.label :subcat %><br />
    <%= f.text_field :subcat %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_index_admin_data.html.erb
<dl class="accordion">
	<dt>
		<span style="color: green">Admin data</span>
	</dt>
	
	<dd>
		<%= @params.keys %><br />
		
		<% if @params['genre'] != nil %>
			@params['genre'] => <%= @params['genre'] %>
		<% else %>
			@params['genre'] => nil
		<% end %>
		<br />

		@genre => <%= @genre %>
		<br />
		
		@genres => <%= @genres %>
		<br />
		
		session[:doc_num] => <%= session[:doc_num] %>
		<br />
		
		session[:genre] => <%= session[:genre] %>
		<br />
		
		<% if flash['message'] != nil %>
			<%= flash['message'] %>
		<% end %>	
	</dd>
</dl>

app/views/articles/_index_header.html.erb
<div>
	<%= form_tag('#', :method => :get) do %>
		<span id="top">
			読み込むページ数
		</span>
		<!-- 	REF => http://d.hatena.ne.jp/utadaq/20080506	 -->
		<%= text_field_tag "doc_num", @current_num || '', :size => '1', :style => "text-align: right;" %>
		
		<span style="background-color: green; color: white">
			ジャンル</span>
<!-- 			<select name="genre_name"> -->
			<select name="genre">
				<% @genres.length.times do |i| %>
					<option value="<%= @genres[@genres.keys[i]] %>" 
								<%#= params['genre_name'] == i.to_s ? "selected" : '' %>
							<% if session[:genre] %>
								<%= session[:genre] == @genres[@genres.keys[i]] ? "selected" : '' %>
							<% else %>
								<%= params['genre'] == @genres[@genres.keys[i]] ? "selected" : '' %>
							<% end %>
								
						>
							<%= @genres.keys[i] %>
							
					</option>
				<% end %>
			</select>
		</span>

		<%= submit_tag "Go" %>

		<span style="background-color: green; color: white">
			記事総数</span>
			
			<% if @objects != nil %>
				<%= @objects.length %>
			<% else %>
				0
			<% end %>
		</span>
		
		|
		<%= link_to "Admin", genres_path, :class => "a_blue" %>
		
	<% end %> <%#= form_tag('#', :method => :get) do %>
	
</div>

app/views/articles/_index_objects_loop.html.erb
<% @objects.each_with_index do |item, i| %>

	<%= render :partial => "index_objects_loop_content", :locals => {:i => i, :item => item} %>
	<%#= render "index_objecrs_loop_content", :locals => {:i => i, :item => item} %>


<% end %>

app/views/articles/_index_objects_loop_content.html.erb
<%= i %>. <%= link_to item.content, item['href'], :target => "_blank" %>

<% if i != 0 and i % 10 == 0 %>

	<hr />

<% end %>



<br />

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<!-- REF=> http://penguin-web.dyndns.org/mountain/blogs/358 -->

<%= render "index_header" %>

<!-- <span id="top"></span> -->

<hr />

<%= render "index_admin_data" %>

<hr /> <!-- -------------------------------------------------- -->

	<% @category_names.each do |item| %>
	
		<%= link_to item, "##{item}" %> | 
	
	<% end %> 

<hr />

<% @objects.each_with_index do |cats, j| %>
	
	<span style="color: blue;">
<!-- 		<div name="<%#= @category_names[j] %>"> -->
		<div>
			<span id="<%= @category_names[j] %>">
				<%= @category_names[j] %> (<%= cats.size %>) |
			</span>
			
			<span>
				<%= link_to "Top", "#top" %>
			</span>
		</div>
		
		
	</span>
	<hr />
	<% cats.each_with_index do |item, i| %>
	
		<%#= i %> 
		<%= i + 1 %>.
		<%#= link_to item.content, item['href'], :target => "_blank" %>
		<%= link_to raw(item.content), item['href'], :target => "_blank" %>
		<br />
	
		<%# if i != 0 and i % 10 == 0 %>
		<% if (i < 12 and i > 8 and i % 9 == 0) or
				(i >= 12 and i % 10 == 0) 
				%>
		
			<hr />
		<%# elsif i % 10 == 0 %>
		
			<hr />
		
		<% end %>

	
	<% end %>
	
	end<hr />

<% end %>

<hr />
@objects.size: <%= @objects.size %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Line:</b>
  <%= @article.line %>
</p>

<p>
  <b>Url:</b>
  <%= @article.url %>
</p>

<p>
  <b>Src:</b>
  <%= @article.src %>
</p>

<p>
  <b>News time:</b>
  <%= @article.news_time %>
</p>

<p>
  <b>Genre:</b>
  <%= @article.genre %>
</p>

<p>
  <b>Cat:</b>
  <%= @article.cat %>
</p>

<p>
  <b>Subcat:</b>
  <%= @article.subcat %>
</p>

<p>
  <b>Tag:</b>
  <%= @article.tag %>
</p>

<p>
  <b>Memo:</b>
  <%= @article.memo %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>