config/routes.rb
NewsReader3::Application.routes.draw do
  
  resources :keywords

  resources :categories

  resources :genres

  resources :articles

  root :to => "articles#index"

  

end

app/views/layouts/_admin_footer.html.erb
<%= link_to_unless_current 'Genres', genres_path %>&nbsp;|&nbsp;
<%= link_to_unless_current 'Categories', categories_path %>&nbsp;|&nbsp;
<%= link_to_unless_current 'Keywords', keywords_path %>&nbsp;

<hr />
<%= link_to "Back to articles", articles_path, {:doc_num => session[:doc_num]} %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsReader3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <script type="text/javascript">
		$(function() {
			$('dl.accordion>dd').hide();
			$('dl.accordion>dt.opened').nextUntil('dl.accordion>dt').show();
			$('dl.accordion>dt').click(function(e) {
				$(this).toggleClass('opened');
				// $(this).nextUntil('dl.accordion>dt').toggle('fast');
				$(this).nextUntil('dl.accordion>dt').toggle();
			});
			
			
		});		
	</script>
	
	<%= stylesheet_link_tag    "/stylesheets/common" %>
	<%= javascript_include_tag "/javascript/admin" %>
	
</head>
<body>

<%= yield %>

<hr />
<%#= link_to "Back to articles", articles_path, {:doc_num => session[:doc_num]} %>

	<%= render :partial => "layouts/admin_footer" %>
<a name="bottom"></a>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsReader3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  	<script type="text/javascript">
		$(function() {
			$('dl.accordion>dd').hide();
			// $('dl.accordion>dt.opened').nextUntil('dl.accordion>dt').show('fast');
			$('dl.accordion>dt.opened').nextUntil('dl.accordion>dt').show();
			$('dl.accordion>dt').click(function(e) {
				$(this).toggleClass('opened');
				// $(this).nextUntil('dl.accordion>dt').toggle('fast');
				$(this).nextUntil('dl.accordion>dt').toggle();
			});
			
			
			//  Open only one item at a time
			// $('dl.accordion>dd').hide();
			// $('dl.accordion>dt.opened').nextUntil('dl.accordion>dt').show('slow');
			// $('dl.accordion>dt').click(function(e) {
				// $('dl.accordion>dd').hide();
				// $('dl.accordion>dt').removeClass('opened');
				// $(this).toggleClass('opened');
				// $(this).nextUntil('dl.accordion>dt').toggle('slow');
			// });
			
			
			// $('dl.accordion').hide();
// 			
			// $('dl.accordion').click(function(e){
				// // $(this).toggleClass('opened');
				// $(this).show('slow');
			// });
			// $('dl.accordion').accordion();
		});		
	</script>

  
</head>
<body>

<%= yield %>

</body>
</html>